name: publish apk release

on:
  workflow_dispatch:
    # push:
  #   branches: 'main'
  #   tags: 'gradle'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          
      - name: GStreamer
        run:
          sudo apt update && sudo apt install -y ninja-build libgtk-3-dev libmpv-dev mpv

      - name: pip install
        run:
          pip install flet
          
      # - name: modify template
      #   run: |
      #     flutter doctor
      #     flet_version=`flet --version`
      #     echo $flet_version
      #     git clone -b $flet_version https://github.com/flet-dev/flet-build-template.git
      #     sed -i "s/ext\.kotlin_version = '.*'/ext.kotlin_version = '1.9.0'/" flet-build-template/\{\{cookiecutter.out_dir\}\}/android/build.gradle 
      #     cat flet-build-template/\{\{cookiecutter.out_dir\}\}/android/build.gradle 
          
      - name: build apk
        run:
          python -c "from scripts.commands import build; build()"
          # python invoke.tasks.py build
            
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/apk/*.apk
          tag_name: gradle
          token: ${{ secrets.AZ_GITHUB_TOKEN }}
          
